runtime: python39

handlers:
  - url: /
    static_files: src/index.html
    upload: src/index.html

  - url: /(.*)
    static_files: src/\1
    upload: src/(.*)

automatic_scaling:
  max_instances: 1